const std = @import("std");
const Io = std.Io;

const cli_io = @import("cli_io.zig");
const notebook = @import("notebook.zig");

const GeneratedDir = ".zig-cache/zig-lab";
const OutputLimit = 10 * 1024 * 1024;

const Visibility = enum { visible, silent };

pub const RunOptions = struct {
    selected_cell: ?[]const u8 = null,
};

pub const Runner = struct {
    gpa: std.mem.Allocator,
    io: Io,
    globals: std.ArrayList(u8) = .empty,

    pub fn deinit(self: *Runner) void {
        self.globals.deinit(self.gpa);
    }

    pub fn runNotebook(self: *Runner, nb: notebook.Notebook, options: RunOptions) !void {
        try Io.Dir.cwd().createDirPath(self.io, GeneratedDir);

        if (options.selected_cell) |wanted| {
            var found = false;
            for (nb.cells) |cell| {
                if (cell.kind != .zig) continue;

                if (cell.id != null and std.mem.eql(u8, cell.id.?, wanted)) {
                    found = true;
                    try self.executeCell(nb, cell, .visible);
                    break;
                }

                try self.preparePreviousDeclaration(cell);
            }

            if (!found) {
                try cli_io.printErr(self.gpa, self.io, "cell not found: {s}\n", .{wanted});
                return error.CellNotFound;
            }
            return;
        }

        for (nb.cells) |cell| {
            switch (cell.kind) {
                .markdown => try cli_io.print(self.gpa, self.io, "[{d}/{d}] markdown: skipped\n", .{ cell.index + 1, nb.cells.len }),
                .zig => try self.executeCell(nb, cell, .visible),
                .other => {},
            }
        }
    }

    pub fn checkNotebook(self: *Runner, nb: notebook.Notebook) !void {
        try cli_io.print(self.gpa, self.io, "Notebook OK\n\n", .{});
        try cli_io.print(self.gpa, self.io, "Cells:    {d}\n", .{nb.cells.len});
        try cli_io.print(self.gpa, self.io, "Markdown: {d}\n", .{nb.countKind(.markdown)});
        try cli_io.print(self.gpa, self.io, "Zig:      {d}\n", .{nb.countKind(.zig)});
    }

    pub fn exportNotebook(self: *Runner, nb: notebook.Notebook, out_path: ?[]const u8) !void {
        var exported: std.ArrayList(u8) = .empty;
        defer exported.deinit(self.gpa);

        var declarations: std.ArrayList(u8) = .empty;
        defer declarations.deinit(self.gpa);

        var main_body: std.ArrayList(u8) = .empty;
        defer main_body.deinit(self.gpa);

        var tests: std.ArrayList(u8) = .empty;
        defer tests.deinit(self.gpa);

        try exported.appendSlice(self.gpa, "// Generated by Zig-lab.\n");
        try exported.appendSlice(self.gpa, "// Declaration cells stay top-level; run cells are placed in main().\n\n");

        for (nb.cells) |cell| {
            if (cell.kind != .zig) continue;
            const header = try std.fmt.allocPrint(self.gpa, "// cell {d}: {s}\n", .{ cell.index + 1, cell.displayName() });
            defer self.gpa.free(header);

            if (isTestCell(cell.source)) {
                try tests.appendSlice(self.gpa, header);
                try tests.appendSlice(self.gpa, cell.source);
                if (!std.mem.endsWith(u8, cell.source, "\n")) try tests.append(self.gpa, '\n');
                try tests.append(self.gpa, '\n');
            } else if (containsLikelyStatement(cell.source)) {
                try main_body.appendSlice(self.gpa, "    ");
                try main_body.appendSlice(self.gpa, header);
                try appendIndented(self.gpa, &main_body, cell.source);
                try main_body.append(self.gpa, '\n');
            } else {
                try declarations.appendSlice(self.gpa, header);
                try declarations.appendSlice(self.gpa, cell.source);
                if (!std.mem.endsWith(u8, cell.source, "\n")) try declarations.append(self.gpa, '\n');
                try declarations.append(self.gpa, '\n');
            }
        }

        try exported.appendSlice(self.gpa, declarations.items);

        if (main_body.items.len > 0) {
            try exported.appendSlice(self.gpa, "pub fn main() !void {\n");
            try exported.appendSlice(self.gpa, main_body.items);
            try exported.appendSlice(self.gpa, "}\n\n");
        } else {
            try exported.appendSlice(self.gpa, "pub fn main() !void {}\n\n");
        }

        try exported.appendSlice(self.gpa, tests.items);

        if (out_path) |path| {
            try Io.Dir.cwd().writeFile(self.io, .{
                .sub_path = path,
                .data = exported.items,
            });
            try cli_io.print(self.gpa, self.io, "exported: {s}\n", .{path});
        } else {
            try cli_io.write(self.io, exported.items);
        }
    }

    fn preparePreviousDeclaration(self: *Runner, cell: notebook.Cell) !void {
        if (isTestCell(cell.source)) return;

        const source = try self.buildDeclarationSource(cell.source);
        defer self.gpa.free(source);

        const path = try self.writeGeneratedSource(cell.index, "decl", source);
        defer self.gpa.free(path);

        var result = try self.runCommand(&.{ "zig", "build-exe", path, "-fno-emit-bin" });
        defer result.deinit(self.gpa);

        if (result.succeeded()) {
            try self.addGlobal(cell.source);
        }
    }

    fn executeCell(self: *Runner, nb: notebook.Notebook, cell: notebook.Cell, visibility: Visibility) !void {
        if (isTestCell(cell.source)) {
            try self.executeTestCell(nb, cell, visibility);
            return;
        }

        const declaration_source = try self.buildDeclarationSource(cell.source);
        defer self.gpa.free(declaration_source);

        const declaration_path = try self.writeGeneratedSource(cell.index, "decl", declaration_source);
        defer self.gpa.free(declaration_path);

        var declaration_result = try self.runCommand(&.{ "zig", "build-exe", declaration_path, "-fno-emit-bin" });
        defer declaration_result.deinit(self.gpa);

        if (declaration_result.succeeded()) {
            try self.addGlobal(cell.source);
            if (visibility == .visible) {
                try cli_io.print(self.gpa, self.io, "[{d}/{d}] {s}: ready\n", .{ cell.index + 1, nb.cells.len, cell.displayName() });
                try writeCommandOutput(self, declaration_result);
            }
            return;
        }

        if (!containsLikelyStatement(cell.source)) {
            if (visibility == .visible) {
                try cli_io.print(self.gpa, self.io, "[{d}/{d}] {s}: failed\n", .{ cell.index + 1, nb.cells.len, cell.displayName() });
                try writeCommandOutput(self, declaration_result);
            }
            return error.CellFailed;
        }

        const run_source = try self.buildRunSource(cell.source);
        defer self.gpa.free(run_source);

        const run_path = try self.writeGeneratedSource(cell.index, "run", run_source);
        defer self.gpa.free(run_path);

        var run_result = try self.runCommand(&.{ "zig", "run", run_path });
        defer run_result.deinit(self.gpa);

        if (visibility == .visible) {
            const status: []const u8 = if (run_result.succeeded()) "ran" else "failed";
            try cli_io.print(self.gpa, self.io, "[{d}/{d}] {s}: {s}\n", .{ cell.index + 1, nb.cells.len, cell.displayName(), status });
            try writeCommandOutput(self, run_result);
        }

        if (!run_result.succeeded()) return error.CellFailed;
    }

    fn executeTestCell(self: *Runner, nb: notebook.Notebook, cell: notebook.Cell, visibility: Visibility) !void {
        const source = try self.buildTestSource(cell.source);
        defer self.gpa.free(source);

        const path = try self.writeGeneratedSource(cell.index, "test", source);
        defer self.gpa.free(path);

        var result = try self.runCommand(&.{ "zig", "test", path });
        defer result.deinit(self.gpa);

        if (visibility == .visible) {
            const status: []const u8 = if (result.succeeded()) "passed" else "failed";
            try cli_io.print(self.gpa, self.io, "[{d}/{d}] {s}: test {s}\n", .{ cell.index + 1, nb.cells.len, cell.displayName(), status });
            try writeCommandOutput(self, result);
            if (result.succeeded() and result.stdout.len == 0 and result.stderr.len == 0) {
                try cli_io.print(self.gpa, self.io, "All tests passed.\n", .{});
            }
        }

        if (!result.succeeded()) return error.CellFailed;
    }

    fn buildDeclarationSource(self: *Runner, source: []const u8) ![]u8 {
        var output: std.ArrayList(u8) = .empty;
        errdefer output.deinit(self.gpa);

        try output.appendSlice(self.gpa, "// Generated by Zig-lab for declaration checking.\n\n");
        try output.appendSlice(self.gpa, self.globals.items);
        try output.appendSlice(self.gpa, source);
        if (!std.mem.endsWith(u8, source, "\n")) try output.append(self.gpa, '\n');
        try output.appendSlice(self.gpa, "\npub fn main() !void {}\n");

        return output.toOwnedSlice(self.gpa);
    }

    fn buildRunSource(self: *Runner, source: []const u8) ![]u8 {
        var output: std.ArrayList(u8) = .empty;
        errdefer output.deinit(self.gpa);

        try output.appendSlice(self.gpa, "// Generated by Zig-lab for cell execution.\n\n");
        try output.appendSlice(self.gpa, self.globals.items);
        try output.appendSlice(self.gpa, "pub fn main() !void {\n");
        try appendIndented(self.gpa, &output, source);
        try output.appendSlice(self.gpa, "\n}\n");

        return output.toOwnedSlice(self.gpa);
    }

    fn buildTestSource(self: *Runner, source: []const u8) ![]u8 {
        var output: std.ArrayList(u8) = .empty;
        errdefer output.deinit(self.gpa);

        try output.appendSlice(self.gpa, "// Generated by Zig-lab for test execution.\n\n");
        try output.appendSlice(self.gpa, self.globals.items);
        try output.appendSlice(self.gpa, source);
        if (!std.mem.endsWith(u8, source, "\n")) try output.append(self.gpa, '\n');

        return output.toOwnedSlice(self.gpa);
    }

    fn addGlobal(self: *Runner, source: []const u8) !void {
        try self.globals.appendSlice(self.gpa, source);
        if (!std.mem.endsWith(u8, source, "\n")) try self.globals.append(self.gpa, '\n');
        try self.globals.append(self.gpa, '\n');
    }

    fn writeGeneratedSource(self: *Runner, cell_index: usize, suffix: []const u8, source: []const u8) ![]u8 {
        const path = try std.fmt.allocPrint(self.gpa, GeneratedDir ++ "/cell_{d}_{s}.zig", .{ cell_index + 1, suffix });
        errdefer self.gpa.free(path);

        try Io.Dir.cwd().writeFile(self.io, .{
            .sub_path = path,
            .data = source,
        });

        return path;
    }

    fn runCommand(self: *Runner, argv: []const []const u8) !CommandResult {
        const result = try std.process.run(self.gpa, self.io, .{
            .argv = argv,
            .stdout_limit = .limited(OutputLimit),
            .stderr_limit = .limited(OutputLimit),
        });

        return .{
            .term = result.term,
            .stdout = result.stdout,
            .stderr = result.stderr,
        };
    }
};

const CommandResult = struct {
    term: std.process.Child.Term,
    stdout: []u8,
    stderr: []u8,

    fn deinit(self: *CommandResult, gpa: std.mem.Allocator) void {
        gpa.free(self.stdout);
        gpa.free(self.stderr);
        self.* = undefined;
    }

    fn succeeded(self: CommandResult) bool {
        return switch (self.term) {
            .exited => |code| code == 0,
            else => false,
        };
    }
};

fn writeCommandOutput(runner: *Runner, result: CommandResult) !void {
    if (result.stdout.len > 0) {
        try cli_io.write(runner.io, result.stdout);
        if (!std.mem.endsWith(u8, result.stdout, "\n")) try cli_io.write(runner.io, "\n");
    }
    if (result.stderr.len > 0) {
        try cli_io.write(runner.io, result.stderr);
        if (!std.mem.endsWith(u8, result.stderr, "\n")) try cli_io.write(runner.io, "\n");
    }
}

fn appendIndented(gpa: std.mem.Allocator, output: *std.ArrayList(u8), source: []const u8) !void {
    var offset: usize = 0;
    while (offset < source.len) {
        const newline_index = std.mem.indexOfScalarPos(u8, source, offset, '\n') orelse source.len;
        const line = source[offset..newline_index];
        if (line.len > 0) {
            try output.appendSlice(gpa, "    ");
            try output.appendSlice(gpa, line);
        }
        try output.append(gpa, '\n');
        offset = if (newline_index < source.len) newline_index + 1 else source.len;
    }
}

fn isTestCell(source: []const u8) bool {
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (std.mem.startsWith(u8, trimmed, "test ")) return true;
    }
    return false;
}

fn containsLikelyStatement(source: []const u8) bool {
    if (startsAsFunctionDeclaration(source)) return false;

    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0) continue;
        if (std.mem.startsWith(u8, trimmed, "//")) continue;

        if (startsWithAny(trimmed, &.{
            "std.",
            "try ",
            "_ =",
            "return ",
            "defer ",
            "for ",
            "while ",
            "if ",
            "switch ",
            "break",
            "continue",
        })) return true;

        if (std.mem.endsWith(u8, trimmed, ";") and !startsWithAny(trimmed, &.{
            "const ",
            "var ",
            "fn ",
            "pub ",
            "test ",
            "extern ",
            "export ",
            "comptime ",
            "usingnamespace ",
        })) return true;
    }
    return false;
}

fn startsAsFunctionDeclaration(source: []const u8) bool {
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0) continue;
        if (std.mem.startsWith(u8, trimmed, "//")) continue;
        return std.mem.startsWith(u8, trimmed, "fn ") or std.mem.startsWith(u8, trimmed, "pub fn ");
    }
    return false;
}

fn startsWithAny(value: []const u8, needles: []const []const u8) bool {
    for (needles) |needle| {
        if (std.mem.startsWith(u8, value, needle)) return true;
    }
    return false;
}

test "statement detection catches simple print cells" {
    try std.testing.expect(containsLikelyStatement(
        \\const name = "Zig-lab";
        \\std.debug.print("hello {s}\n", .{name});
    ));
}
